# permissions for end users to view flippers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flipper-controller
    app.kubernetes.io/managed-by: kustomize
  name: flipper-viewer-role
rules:
- apiGroups:
  - apps.flipper.io
  resources:
  - flippers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.flipper.io
  resources:
  - flippers/status
  verbs:
  - get
