# deployment with label mesh: "true"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    mesh: "true"
  namespace: mesh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      mesh: "true"
  template:
    metadata:
      labels:
        app: nginx
        mesh: "true"
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80